//
//  DataStore.swift
//  OnScrollListener
//
//  Created by Stephanie Diep on 2021-01-04.
//

import SwiftUI

class DataStore: ObservableObject {
    @Published var text: String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam mattis sapien mattis velit luctus, at blandit mauris ornare. Morbi in metus ut ipsum blandit molestie. Phasellus dictum ante semper, fringilla neque quis, condimentum augue. Aliquam tincidunt pellentesque dolor. Vestibulum vitae nunc malesuada, accumsan turpis sit amet, lacinia ipsum. Aliquam laoreet urna elementum dolor dictum lobortis. Curabitur vel nibh enim. Aenean ultrices vitae orci ac pharetra. Maecenas congue felis mauris, ut vulputate lacus pharetra non. Sed condimentum quam id ligula tristique, vel posuere urna auctor. Curabitur sit amet placerat quam. Proin leo leo, dignissim egestas justo quis, lacinia vulputate enim. Pellentesque ex eros, pulvinar sed ornare quis, imperdiet ut diam. Quisque in imperdiet neque. Vivamus vel felis sollicitudin, mattis nisl vel, laoreet erat. Etiam mattis, lectus a auctor tempor, sem diam pharetra orci, et interdum risus risus quis tortor. Nam in sapien eu nulla cursus pulvinar et ac urna. Praesent nec facilisis eros. Nam elit magna, maximus non est sit amet, vehicula rhoncus felis. Curabitur non pretium nulla. Proin aliquet ut felis non pharetra. Pellentesque pharetra sollicitudin lacinia. Suspendisse lobortis a turpis id fringilla. Suspendisse lobortis ultricies velit. Suspendisse eget dui et neque dapibus tempor. Donec metus augue, efficitur eu metus vitae, iaculis tristique eros. Morbi vel mattis est. Pellentesque lacinia ipsum sit amet ligula condimentum eleifend. Sed placerat est non condimentum ultrices. In ut felis quis dolor venenatis tincidunt. Morbi accumsan pharetra tellus in volutpat. Vestibulum porta lorem felis, eu ornare felis dapibus a. Maecenas sed justo semper, fringilla mi quis, maximus nisi. Ut dignissim tellus ac vulputate rhoncus. Pellentesque ac nibh tempus, accumsan justo quis, aliquet mauris. Proin consectetur, erat non mollis luctus, nibh metus vestibulum diam, mattis efficitur nisl risus in augue. Pellentesque lacinia faucibus felis. Curabitur at ipsum tincidunt, placerat dolor eu, dictum augue. Ut ante libero, faucibus in neque id, pretium posuere ex. Ut elementum malesuada erat ac tincidunt. In lacinia maximus massa non rutrum. Cras vel pellentesque augue. Ut blandit magna odio, eu mollis augue rhoncus non. Integer nec justo in ex pellentesque consequat. Aenean semper turpis dolor, lacinia semper nibh rhoncus id. Morbi rhoncus varius faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc sed odio at risus placerat tempus eu nec purus. Morbi in tellus non enim aliquet accumsan vitae sed magna. Curabitur est erat, ornare non elit in, pretium elementum urna. Vestibulum vel consequat tortor. Sed iaculis enim a nibh aliquam, vel finibus est egestas. Aliquam tincidunt purus a sem malesuada facilisis. In ultrices quam magna, eu fermentum erat blandit ut. Suspendisse turpis magna, mattis nec sem vel, porta euismod enim."
    
}
